#!/usr/bin/env python3

 # -*- coding: utf-8 -*- 

from database import *
from helpers import *
from print_helpers import *
import cgi

print_head()
print_header(check_cookie())

form = cgi.FieldStorage()
data = form.keys()
fields = {}
for i in data:
	fields[i] = form.getfirst(i)

err = 1
if len(fields) < 4:
	print_alert("You should enter all fields!")
else:
	if not check_name_input(fields["first_name"]) or not check_name_input(fields["last_name"]):
		print_alert("You should enter only characters in name!")
	elif not check_email_input(fields["email"]):
		print_alert("You should enter email like example@mail!")
	elif not check_pass_input(fields["pass"]):
		print_alert("You should enter more than 7 symbols for password!")
	elif check_user(fields["email"]):
		print_alert("User with this email already registered!")
	else:
		create_user(fields)
		err = 0
if err:
	print_reg()
else:
	print_ok("Registration complete!")

print_footer()