#!/usr/bin/env python3

 # -*- coding: utf-8 -*- 

from database import *
from helpers import *
from print_helpers import *
import cgi

print_head()
print_header(check_cookie())
print_search("journals")

pid = cgi.FieldStorage().getfirst("id")

print_journal_info(pid)

offset = cgi.FieldStorage().getfirst("page")

off = calculate_offset(offset)
p_range = off[0]
offset = off[1]

stor = get_storage_params(cgi.FieldStorage())
params = stor[0]
param_str = stor[1]

print_journal_issues(pid)

print_footer()