#!/usr/bin/env python3

 # -*- coding: utf-8 -*- 

from helpers import *
import cgi

params = cgi.FieldStorage()

art_id = params.getfirst("id")
vote = params.getfirst("vote")

update_article_votes(art_id, vote)

print ("Content-Type: text/plain")
print ("Refresh: 0; url=article?id=%s" % art_id)
print ()
print ("Redirecting...")